/**
 * onStageGrouping.js
 *
 * PURE grouping logic for the collapsible On Stage board.
 * No DOM, no network, no React, no framework. Input in, output out.
 *
 * Used by the Dashboard On Stage tab (Up Next / Live Requests / Handled).
 * Written in Claude, frozen, reproduced byte-for-byte by the agent, SHA-verified.
 * Do not edit this file in Emergent.
 */

/**
 * Normalize a free-text value for use as a grouping key.
 * Trims, lowercases, and collapses internal whitespace.
 */
function normalizeKeyText(value) {
  if (value === null || value === undefined) return '';
  return String(value).trim().toLowerCase().replace(/\s+/g, ' ');
}

/**
 * Read a timestamp off an item as milliseconds since epoch.
 * timeField 'updated_at' falls back to created_at when absent.
 * Unparseable or missing dates return 0 so they sort to the far end
 * rather than poisoning the comparison with NaN.
 */
function readTime(item, timeField) {
  if (!item) return 0;
  var raw = timeField === 'updated_at'
    ? (item.updated_at || item.created_at)
    : item.created_at;
  if (!raw) return 0;
  var ms = new Date(raw).getTime();
  return isNaN(ms) ? 0 : ms;
}

/**
 * Is this item an audience suggestion rather than a real request?
 * Suggestions are free text and carry no song_id.
 */
function isSuggestionItem(item) {
  return !!item && item.type === 'suggestion';
}

/**
 * Grouping key for COLLAPSE BY SONG.
 * Prefers song_id. Falls back to normalized title + artist so that a request
 * with a missing song_id still folds with its twins instead of standing alone.
 */
function songKeyFor(item) {
  if (item && item.song_id) return 'id:' + String(item.song_id);
  var title = normalizeKeyText(item && item.song_title);
  var artist = normalizeKeyText(item && item.song_artist);
  return 'ta:' + title + '|' + artist;
}

/**
 * Grouping key for COLLAPSE BY REQUESTER.
 * Normalized display name. Deliberately name-based, not email-based: most of
 * the crowd never leaves an email, and the name is what the musician sees.
 * Known and accepted consequence: two different people who both type "Mike"
 * fold into one card.
 */
function requesterKeyFor(item) {
  var name = normalizeKeyText(item && item.requester_name);
  if (!name) return 'anon:';
  return 'name:' + name;
}

/**
 * Build one group object.
 */
function makeGroup(key, kind, items, timeField, order) {
  // Items inside a group always read oldest-first, so the expanded modal
  // lists people in the order they actually asked.
  var sorted = items.slice().sort(function (a, b) {
    return readTime(a, 'created_at') - readTime(b, 'created_at');
  });

  var times = sorted.map(function (it) { return readTime(it, timeField); });
  // A group sorts by its oldest member when the board is oldest-first, and by
  // its newest member when the board is newest-first. Either way the group sits
  // where a human would expect to find it.
  var stamp = order === 'newest' ? Math.max.apply(null, times) : Math.min.apply(null, times);

  return {
    key: key,
    kind: kind,
    count: sorted.length,
    items: sorted,
    lead: sorted[0],
    isSuggestion: isSuggestionItem(sorted[0]),
    timestamp: stamp
  };
}

/**
 * groupOnStageItems
 *
 * @param {Array}  items    Merged, already-normalized request/suggestion objects.
 *                          Requests are { type: 'request', ... }, suggestions are
 *                          { type: 'suggestion', ... }.
 * @param {Object} options
 *   @param {String} mode       'none' | 'song' | 'requester'
 *   @param {String} order      'oldest' | 'newest'          (default 'oldest')
 *   @param {String} timeField  'created_at' | 'updated_at'  (default 'created_at')
 *   @param {Number} limit      max number of GROUPS returned (default 0 = no cap)
 *
 * @returns {Array} groups, ordered for render.
 *
 * MODE BEHAVIOUR
 *   'none'      Every item is its own group (kind 'single'). Identical to the
 *               board as it renders today. Nothing folds.
 *   'song'      Requests fold by song. Suggestions NEVER fold (they are free
 *               text with no song_id) and are forced after every song group.
 *   'requester' Everything folds by person, suggestions included, because a
 *               suggestion is still a song that person asked for.
 *
 * LIMIT is applied to GROUPS, after grouping and ordering. This is load-bearing
 * for the Handled panel: it caps at ten groups, never ten items, so forty
 * requests for one song occupy one slot instead of burying every other song.
 */
function groupOnStageItems(items, options) {
  var opts = options || {};
  var mode = opts.mode || 'none';
  var order = opts.order === 'newest' ? 'newest' : 'oldest';
  var timeField = opts.timeField === 'updated_at' ? 'updated_at' : 'created_at';
  var limit = typeof opts.limit === 'number' && opts.limit > 0 ? opts.limit : 0;

  var safeItems = Array.isArray(items) ? items.filter(function (it) { return !!it; }) : [];

  var groups = [];

  if (mode === 'none') {
    groups = safeItems.map(function (it, idx) {
      return makeGroup(
        'single:' + (it.id !== undefined && it.id !== null ? String(it.id) : 'idx' + idx),
        'single',
        [it],
        timeField,
        order
      );
    });
  } else if (mode === 'song') {
    var songBuckets = {};
    var songOrder = [];
    var loneSuggestions = [];

    safeItems.forEach(function (it, idx) {
      if (isSuggestionItem(it)) {
        loneSuggestions.push(makeGroup(
          'suggestion:' + (it.id !== undefined && it.id !== null ? String(it.id) : 'idx' + idx),
          'single',
          [it],
          timeField,
          order
        ));
        return;
      }
      var key = songKeyFor(it);
      if (!songBuckets[key]) {
        songBuckets[key] = [];
        songOrder.push(key);
      }
      songBuckets[key].push(it);
    });

    var songGroups = songOrder.map(function (key) {
      var bucket = songBuckets[key];
      return makeGroup(key, bucket.length > 1 ? 'song' : 'single', bucket, timeField, order);
    });

    songGroups = orderGroups(songGroups, order);
    loneSuggestions = orderGroups(loneSuggestions, order);

    // Suggestions always trail the song groups.
    groups = songGroups.concat(loneSuggestions);

    return limit ? groups.slice(0, limit) : groups;
  } else if (mode === 'requester') {
    var reqBuckets = {};
    var reqOrder = [];

    safeItems.forEach(function (it) {
      var key = requesterKeyFor(it);
      if (!reqBuckets[key]) {
        reqBuckets[key] = [];
        reqOrder.push(key);
      }
      reqBuckets[key].push(it);
    });

    groups = reqOrder.map(function (key) {
      var bucket = reqBuckets[key];
      return makeGroup(key, bucket.length > 1 ? 'requester' : 'single', bucket, timeField, order);
    });
  } else {
    // Unknown mode is treated as 'none' rather than throwing. A bad toggle value
    // must never blank the board mid-set.
    groups = safeItems.map(function (it, idx) {
      return makeGroup('single:' + (it.id !== undefined && it.id !== null ? String(it.id) : 'idx' + idx), 'single', [it], timeField, order);
    });
  }

  groups = orderGroups(groups, order);

  return limit ? groups.slice(0, limit) : groups;
}

/**
 * Order groups by their timestamp. Ties break on key so the order is stable
 * across re-renders and a card never jumps under a thumb mid-tap.
 */
function orderGroups(groups, order) {
  return groups.slice().sort(function (a, b) {
    var delta = order === 'newest'
      ? b.timestamp - a.timestamp
      : a.timestamp - b.timestamp;
    if (delta !== 0) return delta;
    return a.key < b.key ? -1 : (a.key > b.key ? 1 : 0);
  });
}

/**
 * Every request id inside a group. This is what the collapsed card's bulk
 * Played / Skip / Up Next actions fire against, one call per id, client side.
 * Suggestion ids are excluded: suggestions use a different endpoint entirely
 * and must never be handed to updateRequestStatus.
 */
function requestIdsIn(group) {
  if (!group || !Array.isArray(group.items)) return [];
  return group.items
    .filter(function (it) { return it && !isSuggestionItem(it) && it.id !== undefined && it.id !== null; })
    .map(function (it) { return it.id; });
}

/**
 * Every suggestion id inside a group, for the same reason in reverse.
 */
function suggestionIdsIn(group) {
  if (!group || !Array.isArray(group.items)) return [];
  return group.items
    .filter(function (it) { return it && isSuggestionItem(it) && it.id !== undefined && it.id !== null; })
    .map(function (it) { return it.id; });
}

export {
  groupOnStageItems,
  requestIdsIn,
  suggestionIdsIn,
  normalizeKeyText,
  songKeyFor,
  requesterKeyFor
};
