import React, { useState, useMemo, useEffect } from 'react';
import axios from 'axios';
import { groupOnStageItems } from './onStageGrouping';

/**
 * onStageCompanionBoard.jsx
 *
 * The PUBLIC, view-only band-member companion board for the on-stage link
 * (/on-stage/:slug). Same visual structure as onStageBoard.jsx (the
 * authenticated dashboard's On Stage tab): Setlist / Up Next / Live
 * Requests / Handled, plus the View Options collapse-by drawer. Every
 * mutating action from that file has been removed - no Play/Skip/Up Next,
 * no Restore, no Match to Song, no Learn it later, no drag-to-reorder, no
 * bulk actions, no Learn Later bookmarks (per Bryce: band members get zero
 * write access). Tapping a song still opens its chart, everywhere,
 * including Handled - that's one thing the dashboard's own board doesn't
 * even do today.
 *
 * Also deliberately hides requester email ("email provided" icon) and tip
 * amount/tip-clicked indicators that onStageBoard.jsx shows. Those are fine
 * on an authenticated dashboard only the musician sees; this is a link that
 * can end up on any audience member's phone, so what a specific person
 * tipped is not shown here.
 *
 * Self-contained: own axios import, own API const. No auth token is ever
 * read or sent by this file - every request it makes is to a public,
 * no-auth endpoint (the companion setlists endpoint, keyed by the
 * musician's real slug).
 *
 * SCOPING CONTRACT: this component does NOT decide which show to display,
 * and does NOT render a "No Active Show" or "which show are you at" state.
 * It assumes `currentShow` is already a single, resolved, valid show,
 * exactly like the dashboard gates OnStageBoard on `currentShow &&` before
 * ever rendering it. The caller (OnStageInterface) is responsible for
 * reading `onstage_resolution` from GET /onstage/{onstage_slug} and only
 * rendering this component once that resolution is unambiguous (handling
 * the zero-shows-live and two-or-more-shows-live cases itself).
 *
 * Written in Claude, placed byte-for-byte by the agent, SHA-verified.
 * Do not edit this file in Emergent.
 */

const API = `${process.env.REACT_APP_BACKEND_URL}/api`;

const MODE_KEY = 'onstage_companion_collapse_mode';
const DRAWER_KEY = 'onstage_companion_view_options_expanded';
const SETLIST_ID_KEY_PREFIX = 'onstage_companion_selected_setlist_id_';
const SETLIST_PLAYED_PREFIX = 'onstage_companion_setlist_played_';
const SETLIST_COLLAPSED_KEY = 'onstage_companion_setlist_collapsed';
const UPNEXT_COLLAPSED_KEY = 'onstage_companion_upnext_collapsed';
const LIVE_COLLAPSED_KEY = 'onstage_companion_live_collapsed';
const COMPLETED_COLLAPSED_KEY = 'onstage_companion_completed_collapsed';

const MODE_HINTS = {
  none: 'Every request shown separately.',
  song: 'Duplicate requests for the same song fold into one card. Suggestions never fold.',
  requester: 'All songs from one person fold into one card.'
};

/* ------------------------------------------------------------------
   View Options drawer. Identical in spirit to onStageBoard.jsx's - a pure
   display preference, no mutation, safe to leave exactly as-is.
   ------------------------------------------------------------------ */
function ViewOptions({ mode, setMode, expanded, setExpanded }) {
  return (
    <div data-testid="onstage-companion-view-options" className="bg-gray-800 rounded-xl">
      <button
        type="button"
        data-testid="onstage-companion-view-options-toggle"
        onClick={() => setExpanded(!expanded)}
        className="w-full p-3 flex items-center justify-between text-left hover:bg-gray-750"
      >
        <span className="text-sm font-medium text-gray-300">View Options</span>
        <svg className={`w-4 h-4 text-gray-400 shrink-0 transition-transform ${expanded ? 'rotate-180' : ''}`} fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
        </svg>
      </button>
      {expanded && (
        <div className="px-3 pb-3 border-t border-gray-700 pt-3">
          <div className="flex items-center gap-3 flex-wrap">
            <span className="text-sm text-gray-400 shrink-0">Collapse by:</span>
            <div className="flex bg-gray-900 rounded-lg p-1">
              {[['none', 'Off'], ['song', 'Song'], ['requester', 'Requester']].map(([value, label]) => (
                <button
                  key={value}
                  type="button"
                  data-testid={`onstage-companion-collapse-${value}`}
                  onClick={() => setMode(value)}
                  className={`px-4 py-2 rounded-md text-sm font-medium transition duration-300 ${
                    mode === value ? 'bg-purple-600 text-white' : 'text-gray-400 hover:text-white'
                  }`}
                >
                  {label}
                </button>
              ))}
            </div>
          </div>
          <div className="text-xs text-gray-500 mt-2">{MODE_HINTS[mode] || MODE_HINTS.none}</div>
        </div>
      )}
    </div>
  );
}

/* ------------------------------------------------------------------
   Chart button. Same behaviour and testid as onStageBoard.jsx's copy -
   purely read-only (opens a viewer or a new tab), safe to reuse verbatim.
   ------------------------------------------------------------------ */
function ChartButton({ item, songs, setOpenChordpro }) {
  const chartSong = songs.find((s) => s.id === item.song_id) || {};
  const hasChart = ((chartSong.chart_type === 'link' || chartSong.chart_type === 'pdf') && chartSong.chart_url) || (chartSong.chart_type === 'chordpro' && chartSong.chart_chordpro);
  if (!hasChart) return null;
  return (
    <button
      type="button"
      data-testid="onstage-companion-charts-button"
      onClick={() => {
        if (chartSong.chart_type === 'chordpro') {
          setOpenChordpro({ chordpro: chartSong.chart_chordpro, title: chartSong.song_title || chartSong.title || item.song_title, id: chartSong.id, transpose: chartSong.transpose || 0 });
        } else {
          window.open(chartSong.chart_url, '_blank');
        }
      }}
      className="bg-indigo-600 hover:bg-indigo-700 text-white px-2 py-1 rounded text-xs transition duration-300"
      title="Open chart"
    >
      📄 Charts
    </button>
  );
}

/* ------------------------------------------------------------------
   Small "in setlist" tag, identical to onStageBoard.jsx's - purely
   informational, no change to any card's meaning or behaviour.
   ------------------------------------------------------------------ */
function InSetlistTag({ songId, setlistSongIdSet }) {
  if (!songId || !setlistSongIdSet.has(songId)) return null;
  return (
    <span className="text-[10px] bg-amber-900/40 border border-amber-600 text-amber-200 font-bold px-2 py-0.5 rounded-full shrink-0">
      in setlist
    </span>
  );
}

/* ==================================================================
   MAIN
   ================================================================== */
export default function OnStageCompanionBoard({
  requests = [],
  songSuggestions = [],
  songs = [],
  currentShow,
  slug,
  setOpenChordpro
}) {
  const [mode, setModeState] = useState(() => {
    try {
      const saved = localStorage.getItem(MODE_KEY);
      return saved === 'song' || saved === 'requester' ? saved : 'none';
    } catch { return 'none'; }
  });
  const [viewOptionsExpanded, setViewOptionsExpandedState] = useState(() => {
    try { return localStorage.getItem(DRAWER_KEY) !== 'false'; } catch { return true; }
  });
  const [openGroup, setOpenGroup] = useState(null);

  const [setlists, setSetlistsState] = useState([]);
  const [selectedSetlistId, setSelectedSetlistIdState] = useState(() => {
    try { return localStorage.getItem(SETLIST_ID_KEY_PREFIX + (slug || '')) || ''; } catch { return ''; }
  });
  const [playedSetlistSongIds, setPlayedSetlistSongIds] = useState(() => new Set());
  const [setlistCollapsed, setSetlistCollapsedState] = useState(() => {
    try { return localStorage.getItem(SETLIST_COLLAPSED_KEY) === 'true'; } catch { return false; }
  });
  const [upNextCollapsed, setUpNextCollapsedState] = useState(() => {
    try { return localStorage.getItem(UPNEXT_COLLAPSED_KEY) === 'true'; } catch { return false; }
  });
  const [liveCollapsed, setLiveCollapsedState] = useState(() => {
    try { return localStorage.getItem(LIVE_COLLAPSED_KEY) === 'true'; } catch { return false; }
  });
  const [completedSectionCollapsed, setCompletedSectionCollapsedState] = useState(() => {
    try { return localStorage.getItem(COMPLETED_COLLAPSED_KEY) === 'true'; } catch { return false; }
  });

  const setMode = (v) => {
    setModeState(v);
    try { localStorage.setItem(MODE_KEY, v); } catch {}
  };
  const setViewOptionsExpanded = (v) => {
    setViewOptionsExpandedState(v);
    try { localStorage.setItem(DRAWER_KEY, String(v)); } catch {}
  };
  const setSelectedSetlistId = (id) => {
    setSelectedSetlistIdState(id);
    try { localStorage.setItem(SETLIST_ID_KEY_PREFIX + (slug || ''), id); } catch {}
  };
  const setSetlistCollapsed = (v) => {
    setSetlistCollapsedState(v);
    try { localStorage.setItem(SETLIST_COLLAPSED_KEY, String(v)); } catch {}
  };
  const setUpNextCollapsed = (v) => {
    setUpNextCollapsedState(v);
    try { localStorage.setItem(UPNEXT_COLLAPSED_KEY, String(v)); } catch {}
  };
  const setLiveCollapsed = (v) => {
    setLiveCollapsedState(v);
    try { localStorage.setItem(LIVE_COLLAPSED_KEY, String(v)); } catch {}
  };
  const setCompletedSectionCollapsed = (v) => {
    setCompletedSectionCollapsedState(v);
    try { localStorage.setItem(COMPLETED_COLLAPSED_KEY, String(v)); } catch {}
  };

  /* ---------- setlists: self-contained fetch against the PUBLIC companion
     endpoint, keyed by the musician's real slug. No auth token - this page
     has none. ---------- */
  useEffect(() => {
    if (!slug) return;
    axios.get(`${API}/musicians/${slug}/onstage-companion-setlists`)
      .then((res) => setSetlistsState(Array.isArray(res.data) ? res.data : []))
      .catch(() => {});
  }, [slug]);

  /* ---------- per-setlist local "played" tracking, keyed in localStorage
     per slug + setlist id so two different bands' companion links
     bookmarked on the same phone never collide. Purely local to this
     device - never sent anywhere. ---------- */
  useEffect(() => {
    if (!selectedSetlistId) { setPlayedSetlistSongIds(new Set()); return; }
    try {
      const raw = localStorage.getItem(SETLIST_PLAYED_PREFIX + (slug || '') + '_' + selectedSetlistId);
      setPlayedSetlistSongIds(new Set(raw ? JSON.parse(raw) : []));
    } catch { setPlayedSetlistSongIds(new Set()); }
  }, [selectedSetlistId, slug]);

  const toggleSetlistSongPlayed = (songId) => {
    setPlayedSetlistSongIds((prev) => {
      const next = new Set(prev);
      if (next.has(songId)) next.delete(songId); else next.add(songId);
      try { localStorage.setItem(SETLIST_PLAYED_PREFIX + (slug || '') + '_' + selectedSetlistId, JSON.stringify(Array.from(next))); } catch {}
      return next;
    });
  };

  const showId = currentShow ? currentShow.id : null;

  /* ---------- source lists, matching onStageBoard.jsx's filters exactly ---------- */
  const upNextItems = useMemo(() => (
    requests
      .filter((r) => r.show_id === showId && r.status === 'up_next')
      .map((r) => ({ ...r, type: 'request' }))
  ), [requests, showId]);

  const activeItems = useMemo(() => {
    const activeReqs = requests.filter((r) => r.show_id === showId && ['pending', 'accepted'].includes(r.status)).map((r) => ({ ...r, type: 'request' }));
    const pendingSuggs = songSuggestions.filter((s) => s.show_id === showId && s.status === 'pending').map((s) => ({
      ...s,
      type: 'suggestion',
      song_title: s.suggested_title,
      song_artist: s.suggested_artist,
      dedication: s.message,
      requester_name: s.requester_name
    }));
    return [...activeReqs, ...pendingSuggs];
  }, [requests, songSuggestions, showId]);

  const completedItems = useMemo(() => {
    const completedReqs = requests.filter((r) => r.show_id === showId && ['played', 'rejected'].includes(r.status)).map((r) => ({ ...r, type: 'request' }));
    const handledSuggs = songSuggestions.filter((s) => s.show_id === showId && (s.status === 'learn_later' || s.status === 'rejected')).map((s) => ({
      ...s,
      type: 'suggestion',
      song_title: s.suggested_title,
      song_artist: s.suggested_artist,
      dedication: s.message,
      requester_name: s.requester_name,
      status: s.status === 'learn_later' ? 'learn_later' : 'rejected'
    }));
    return [...completedReqs, ...handledSuggs];
  }, [requests, songSuggestions, showId]);

  /* ---------- setlist derivation ---------- */
  const selectedSetlist = useMemo(() => setlists.find((s) => s.id === selectedSetlistId) || null, [setlists, selectedSetlistId]);
  const setlistSongs = useMemo(() => (
    (selectedSetlist?.song_ids || []).map((id) => songs.find((s) => s.id === id)).filter(Boolean)
  ), [selectedSetlist, songs]);
  const setlistSongIdSet = useMemo(() => new Set(selectedSetlist?.song_ids || []), [selectedSetlist]);
  const liveSongIdCounts = useMemo(() => {
    const counts = new Map();
    [...upNextItems, ...activeItems].forEach((it) => {
      if (it.type !== 'request' || !it.song_id) return;
      counts.set(it.song_id, (counts.get(it.song_id) || 0) + 1);
    });
    return counts;
  }, [upNextItems, activeItems]);

  /* View-only: tapping a setlist song only ever opens its chart (chordpro
     viewer or external link). A song with no chart at all does nothing -
     there is no fallback into a song editor here, unlike the dashboard. */
  const handleTapSetlistSong = (song) => {
    const hasChordpro = song.chart_type === 'chordpro' && song.chart_chordpro;
    const hasExternal = (song.chart_type === 'link' || song.chart_type === 'pdf') && song.chart_url;
    if (hasChordpro) {
      setOpenChordpro({
        chordpro: song.chart_chordpro,
        title: song.title,
        id: song.id,
        transpose: song.transpose || 0,
        setlistOnPlayed: () => toggleSetlistSongPlayed(song.id)
      });
    } else if (hasExternal) {
      window.open(song.chart_url, '_blank');
    }
  };

  /* ---------- grouping (pure, frozen utility - unmodified) ---------- */
  const upNextGroups = useMemo(() => groupOnStageItems(upNextItems, { mode, order: 'oldest', timeField: 'queue_position' }), [upNextItems, mode]);
  const activeGroups = useMemo(() => groupOnStageItems(activeItems, { mode, order: 'oldest', timeField: 'created_at' }), [activeItems, mode]);
  const completedGroups = useMemo(() => groupOnStageItems(completedItems, { mode, order: 'newest', timeField: 'updated_at', limit: 10 }), [completedItems, mode]);

  /* Close a modal whose group has stopped existing (e.g. everything in it
     was just marked played by the leader mid-viewing). */
  useEffect(() => {
    if (!openGroup) return;
    const pool = openGroup.panel === 'upnext' ? upNextGroups : openGroup.panel === 'live' ? activeGroups : completedGroups;
    if (!pool.some((g) => g.key === openGroup.key)) setOpenGroup(null);
  }, [openGroup, upNextGroups, activeGroups, completedGroups]);

  const upNextCount = upNextItems.length;

  /* ================= CARDS (all view-only: no action buttons anywhere) ================= */

  const suggestionCard = (item) => (
    <div key={item.id} className="bg-orange-900/30 rounded-lg p-4 border-l-4 border-orange-400">
      <div className="flex justify-between items-start mb-2">
        <span className="px-2 py-1 rounded-full text-xs font-bold bg-orange-600 text-white">SUGGESTION</span>
      </div>
      <h4 className="font-bold text-lg text-orange-100 break-words">{item.suggested_title || item.song_title}</h4>
      <p className="text-orange-200 break-words">by {item.suggested_artist || item.song_artist}</p>
      <p className="text-sm text-gray-300 mt-2">
        From: <strong className="text-white">{item.requester_name}</strong>
      </p>
      {item.message && (
        <p className="text-sm text-orange-200 mt-1 italic break-words">"{item.message}"</p>
      )}
    </div>
  );

  const singleRequestCard = (group, panel) => {
    const item = group.lead;
    const cardBg = panel === 'upnext' ? 'bg-blue-800/50' : 'bg-purple-800/50';
    const artistCls = panel === 'upnext' ? 'text-blue-200' : 'text-purple-200';
    return (
      <div key={item.id} className={`${cardBg} rounded-lg p-4`}>
        <h4 className="font-bold text-lg text-white flex items-center gap-2 flex-wrap">
          <span className="break-words">{item.song_title}</span>
          <ChartButton item={item} songs={songs} setOpenChordpro={setOpenChordpro} />
          <InSetlistTag songId={item.song_id} setlistSongIdSet={setlistSongIdSet} />
        </h4>
        <p className={`${artistCls} break-words`}>{item.song_artist}</p>
        <p className="text-sm text-gray-300 mt-2">
          From: <strong className="text-white">{item.requester_name}</strong>
        </p>
        {item.dedication && (
          <p className={`text-sm ${artistCls} mt-1 italic break-words`}>"{item.dedication}"</p>
        )}
      </div>
    );
  };

  const songGroupCard = (group, panel) => {
    const lead = group.lead;
    const cardBg = panel === 'upnext' ? 'bg-blue-800/50' : 'bg-purple-800/50';
    const artistCls = panel === 'upnext' ? 'text-blue-200' : 'text-purple-200';
    return (
      <div key={group.key} className={`${cardBg} rounded-lg p-4 border-l-4 border-white/30`}>
        <div className="flex items-start justify-between gap-3">
          <div className="min-w-0">
            <h4 className="font-bold text-lg text-white flex items-center gap-2 flex-wrap">
              <span className="break-words">{lead.song_title}</span>
              <ChartButton item={lead} songs={songs} setOpenChordpro={setOpenChordpro} />
              <InSetlistTag songId={lead.song_id} setlistSongIdSet={setlistSongIdSet} />
            </h4>
            <p className={`${artistCls} break-words`}>{lead.song_artist}</p>
          </div>
          <button
            type="button"
            onClick={() => setOpenGroup({ panel, key: group.key })}
            className="bg-white/20 hover:bg-white/30 text-white px-3 py-1 rounded-full text-sm font-bold transition duration-300 shrink-0"
          >
            {group.count} requests ›
          </button>
        </div>
      </div>
    );
  };

  const requesterGroupCard = (group, panel) => {
    const cardBg = panel === 'upnext' ? 'bg-blue-800/50' : 'bg-purple-800/50';
    const artistCls = panel === 'upnext' ? 'text-blue-200' : 'text-purple-200';
    const names = group.items.slice(0, 3).map((i) => i.song_title).join(', ');
    return (
      <div key={group.key} className={`${cardBg} rounded-lg p-4 border-l-4 border-yellow-400`}>
        <div className="flex items-start justify-between gap-3">
          <div className="min-w-0">
            <h4 className="font-bold text-lg text-white break-words">{group.lead.requester_name || 'No name'}</h4>
            <p className={`text-sm ${artistCls} break-words mt-0.5`}>
              {names}{group.count > 3 ? `, and ${group.count - 3} more` : ''}
            </p>
          </div>
          <button
            type="button"
            onClick={() => setOpenGroup({ panel, key: group.key })}
            className="bg-yellow-600 hover:bg-yellow-700 text-white px-3 py-1 rounded-full text-sm font-bold transition duration-300 shrink-0"
          >
            {group.count} songs ›
          </button>
        </div>
      </div>
    );
  };

  const renderGroup = (group, panel) => {
    if (group.kind === 'song') return songGroupCard(group, panel);
    if (group.kind === 'requester') return requesterGroupCard(group, panel);
    if (group.lead.type === 'suggestion') return suggestionCard(group.lead);
    return singleRequestCard(group, panel);
  };

  /* Handled section's single (non-folded) card: same information as
     onStageBoard.jsx's CompletedRequestItem, minus the Restore button and
     minus the Learn Later bookmark, plus a chart button - the one thing
     Handled doesn't get anywhere else in the app today. */
  const handledItemCard = (item) => {
    const isSuggestion = item.type === 'suggestion';
    const isLearnLater = isSuggestion && item.status === 'learn_later';
    const statusLabel = isLearnLater ? '📚 LEARN LATER' : item.status === 'played' ? '🎵 PLAYED' : item.status === 'rejected' ? '❌ SKIPPED' : item.status;
    const bg = isLearnLater ? 'bg-blue-900/30 border-l-4 border-blue-400' : 'bg-gray-700/50 border-l-4 border-gray-500';
    return (
      <div key={item.id} className={`rounded-lg p-4 ${bg}`}>
        <div className="flex items-center gap-2 mb-2">
          {isSuggestion && (
            <span className="px-2 py-1 rounded-full text-xs font-bold bg-orange-600 text-white">SUGGESTION</span>
          )}
          <span className="px-2 py-1 rounded-full text-xs font-bold bg-gray-600">{statusLabel}</span>
        </div>
        <h4 className="font-bold text-lg text-white flex items-center gap-2 flex-wrap">
          <span className="break-words">{item.song_title}</span>
          {!isSuggestion && <ChartButton item={item} songs={songs} setOpenChordpro={setOpenChordpro} />}
        </h4>
        <p className="text-gray-300 break-words">{item.song_artist}</p>
        <p className="text-sm text-gray-300 mt-2">
          From: <strong className="text-white">{item.requester_name}</strong>
        </p>
        {item.dedication && (
          <p className="text-sm text-purple-200 mt-1 italic break-words">"{item.dedication}"</p>
        )}
      </div>
    );
  };

  /* ================= MODAL (view-only: no action buttons) ================= */
  const modalGroup = (() => {
    if (!openGroup) return null;
    const pool = openGroup.panel === 'upnext' ? upNextGroups : openGroup.panel === 'live' ? activeGroups : completedGroups;
    return pool.find((g) => g.key === openGroup.key) || null;
  })();

  const modal = modalGroup && (
    <div className="fixed inset-0 bg-black/70 flex items-center justify-center z-50 p-4" onClick={() => setOpenGroup(null)}>
      <div className="bg-gray-800 rounded-xl p-6 max-w-2xl w-full max-h-[80vh] overflow-y-auto" onClick={(e) => e.stopPropagation()}>
        <div className="flex justify-between items-start mb-4 gap-4">
          <div className="min-w-0">
            <h3 className="text-xl font-bold break-words">
              {modalGroup.kind === 'requester' ? (modalGroup.lead.requester_name || 'No name') : modalGroup.lead.song_title}
            </h3>
            <p className="text-sm text-gray-400 mt-1 break-words">
              {modalGroup.kind === 'requester'
                ? `Requested ${modalGroup.count} songs`
                : `${modalGroup.count} requests${modalGroup.lead.song_artist ? ` · ${modalGroup.lead.song_artist}` : ''}`}
            </p>
          </div>
          <button onClick={() => setOpenGroup(null)} className="text-gray-400 hover:text-white text-2xl leading-none shrink-0">×</button>
        </div>

        <div className="space-y-3">
          {modalGroup.kind === 'requester'
            ? modalGroup.items.map((it) => (
                <div key={it.id} className={`${it.type === 'suggestion' ? 'bg-orange-900/30 border-l-4 border-orange-400' : 'bg-gray-700/50'} rounded-lg p-3`}>
                  <div className="min-w-0">
                    {it.type === 'suggestion' && (
                      <span className="px-2 py-0.5 rounded-full text-[10px] font-bold bg-orange-600 text-white">SUGGESTION</span>
                    )}
                    <div className="font-bold text-white break-words">{it.song_title}</div>
                    <div className="text-sm text-gray-400 break-words">{it.song_artist}</div>
                    {it.dedication && (
                      <div className="text-sm text-purple-200 italic mt-1 break-words">"{it.dedication}"</div>
                    )}
                  </div>
                </div>
              ))
            : modalGroup.items.map((it) => (
                <div key={it.id} className="bg-gray-700/50 rounded-lg p-3">
                  <div className="flex items-center gap-2 flex-wrap">
                    <strong className="text-white break-words">{it.requester_name || 'No name'}</strong>
                  </div>
                  {it.dedication && (
                    <div className="text-sm text-purple-200 italic mt-1 break-words">"{it.dedication}"</div>
                  )}
                </div>
              ))}
        </div>
      </div>
    </div>
  );

  /* ================= RENDER ================= */
  return (
    <>
      <ViewOptions mode={mode} setMode={setMode} expanded={viewOptionsExpanded} setExpanded={setViewOptionsExpanded} />

      {setlists.length > 0 && (
        <div className="bg-gray-800 rounded-xl p-6 mt-6 mb-6">
          <div className="flex items-center justify-between mb-3 gap-3 flex-wrap">
            <h3 className="text-xl font-bold text-violet-300">
              🎼 Setlist{selectedSetlist ? ` (${setlistSongs.length})` : ''}
            </h3>
            <div className="flex items-center gap-3">
              {setlistSongs.length > 0 && (
                <div className="text-sm text-gray-400">{playedSetlistSongIds.size} played</div>
              )}
              <button onClick={() => setSetlistCollapsed(!setlistCollapsed)} className="text-gray-400 hover:text-white transition-colors">
                {setlistCollapsed ? '▼' : '▲'}
              </button>
            </div>
          </div>
          {!setlistCollapsed && (
            <>
              <select
                data-testid="onstage-companion-setlist-picker"
                value={selectedSetlistId}
                onChange={(e) => setSelectedSetlistId(e.target.value)}
                className="w-full bg-gray-900 border border-gray-700 rounded-lg px-3 py-2 text-sm mb-3 text-white"
              >
                <option value="">Select a setlist…</option>
                {setlists.map((sl) => (
                  <option key={sl.id} value={sl.id}>{sl.name}</option>
                ))}
              </select>
              {selectedSetlist && setlistSongs.length === 0 && (
                <div className="text-center py-4 text-gray-400 text-sm">This setlist has no songs yet.</div>
              )}
              {setlistSongs.length > 0 && (
                <div className="space-y-2 max-h-[420px] overflow-y-auto">
                  {setlistSongs.map((song, idx) => {
                    const matchCount = liveSongIdCounts.get(song.id) || 0;
                    const played = playedSetlistSongIds.has(song.id);
                    const rowBg = played
                      ? 'bg-green-900/20'
                      : matchCount > 0
                        ? 'bg-amber-900/30 border border-amber-600'
                        : 'bg-gray-900/60';
                    return (
                      <div key={song.id} className={`flex items-center gap-2 rounded-lg p-2 ${rowBg} ${played ? 'opacity-50' : ''}`}>
                        <span className="text-xs text-gray-500 w-5 text-right shrink-0">{idx + 1}</span>
                        <button type="button" onClick={() => handleTapSetlistSong(song)} className="flex-1 min-w-0 text-left">
                          <div className={`text-sm font-semibold truncate ${played ? 'line-through text-gray-400' : 'text-white'}`}>{song.title}</div>
                          <div className="text-xs text-gray-400 truncate">{song.artist}</div>
                        </button>
                        {matchCount > 0 && !played && (
                          <span className="text-xs bg-amber-800 text-amber-200 font-bold px-2 py-0.5 rounded-full shrink-0">🔥 {matchCount}</span>
                        )}
                        <button
                          type="button"
                          onClick={() => toggleSetlistSongPlayed(song.id)}
                          title={played ? 'Mark not played' : 'Mark played'}
                          className={`w-6 h-6 rounded-full border shrink-0 flex items-center justify-center text-xs ${played ? 'bg-green-600 border-green-600 text-white' : 'border-gray-600 text-transparent'}`}
                        >
                          ✓
                        </button>
                      </div>
                    );
                  })}
                </div>
              )}
            </>
          )}
        </div>
      )}

      <div className={`grid grid-cols-1 gap-6 ${upNextCount > 0 ? 'lg:grid-cols-3' : 'lg:grid-cols-2'}`}>

        {/* Up Next Panel */}
        {upNextCount > 0 && (
          <div className="bg-blue-900/50 rounded-xl p-6">
            <div className="flex items-center justify-between mb-4">
              <h3 className="text-xl font-bold text-blue-300">🎵 Up Next</h3>
              <div className="flex items-center gap-3">
                <div className="text-sm text-gray-400">{upNextCount} songs</div>
                <button onClick={() => setUpNextCollapsed(!upNextCollapsed)} className="text-gray-400 hover:text-white transition-colors">
                  {upNextCollapsed ? '▼' : '▲'}
                </button>
              </div>
            </div>
            {!upNextCollapsed && (
              <div className="space-y-3">
                {upNextGroups.map((g) => renderGroup(g, 'upnext'))}
              </div>
            )}
          </div>
        )}

        {/* Live Requests Panel */}
        <div className="bg-purple-900/50 rounded-xl p-6">
          <div className="flex items-center justify-between mb-4">
            <h3 className="text-xl font-bold text-purple-300">🎸 Live Requests</h3>
            <div className="flex items-center gap-3">
              <div className="text-sm text-gray-400">{activeItems.length} active</div>
              <button onClick={() => setLiveCollapsed(!liveCollapsed)} className="text-gray-400 hover:text-white transition-colors">
                {liveCollapsed ? '▼' : '▲'}
              </button>
            </div>
          </div>
          {!liveCollapsed && (
            <div className="space-y-3">
              {activeGroups.length === 0 ? (
                <div className="text-center py-8 text-gray-400">
                  <p>No active requests or suggestions</p>
                </div>
              ) : (
                activeGroups.map((g) => renderGroup(g, 'live'))
              )}
            </div>
          )}
        </div>

        {/* Handled Panel */}
        <div className="bg-green-900/50 rounded-xl p-6">
          <div className="mb-4">
            <div className="flex items-center justify-between">
              <div>
                <h3 className="text-xl font-bold text-green-300">✅ Handled</h3>
                <p className="text-sm text-gray-400 mt-1">Played, skipped, or saved for later.</p>
              </div>
              <div className="flex items-center space-x-2">
                <div className="text-sm text-gray-400">
                  {requests.filter((r) => r.show_id === showId && ['played', 'rejected'].includes(r.status)).length} done
                </div>
                <button onClick={() => setCompletedSectionCollapsed(!completedSectionCollapsed)} className="text-gray-400 hover:text-white transition-colors">
                  {completedSectionCollapsed ? '▼' : '▲'}
                </button>
              </div>
            </div>
          </div>

          {!completedSectionCollapsed && (
            <div className="space-y-3">
              {completedGroups.length === 0 ? (
                <div className="text-center py-8 text-gray-400">
                  <p>No completed requests yet</p>
                  <p className="text-sm mt-1">Played and skipped songs will appear here</p>
                </div>
              ) : (
                completedGroups.map((g) => {
                  if (g.kind === 'song' || g.kind === 'requester') {
                    return (
                      <div key={g.key} className={`bg-gray-700/50 rounded-lg p-4 border-l-4 ${g.kind === 'requester' ? 'border-yellow-400' : 'border-white/30'}`}>
                        <div className="flex items-start justify-between gap-3">
                          <div className="min-w-0">
                            <h4 className="font-bold text-white break-words flex items-center gap-2 flex-wrap">
                              <span className="break-words">{g.kind === 'requester' ? (g.lead.requester_name || 'No name') : g.lead.song_title}</span>
                              {g.kind === 'song' && <ChartButton item={g.lead} songs={songs} setOpenChordpro={setOpenChordpro} />}
                            </h4>
                            <p className="text-sm text-gray-400 break-words">
                              {g.kind === 'requester'
                                ? g.items.slice(0, 3).map((i) => i.song_title).join(', ') + (g.count > 3 ? `, and ${g.count - 3} more` : '')
                                : g.lead.song_artist}
                            </p>
                          </div>
                          <button
                            type="button"
                            onClick={() => setOpenGroup({ panel: 'handled', key: g.key })}
                            className={`${g.kind === 'requester' ? 'bg-yellow-600 hover:bg-yellow-700' : 'bg-white/20 hover:bg-white/30'} text-white px-3 py-1 rounded-full text-sm font-bold transition duration-300 shrink-0`}
                          >
                            {g.count} {g.kind === 'requester' ? 'songs' : 'requests'} ›
                          </button>
                        </div>
                      </div>
                    );
                  }
                  return handledItemCard(g.lead);
                })
              )}
            </div>
          )}

          {completedSectionCollapsed && (
            <div className="text-center py-4 text-gray-400">
              <p className="text-sm">Collapsed - Click to expand</p>
            </div>
          )}
        </div>
      </div>

      {modal}
    </>
  );
}
