import React from 'react';

/**
 * songPlayedThanksModal.jsx
 *
 * Blocking "how would you like to say thanks?" modal shown on the audience
 * request page when one of the audience member's own submitted requests
 * gets marked played. Pure presentational component - it owns no state and
 * makes no network calls. All three actions (Tip / Follow / Maybe later)
 * are just callbacks; the caller (AudienceInterface) decides what they
 * actually do (open the existing "About the Artist" Orientation sheet with
 * the tip section expanded, open it to show the Follow links, or just
 * dismiss).
 *
 * showTip / showFollow let the caller hide either action when it wouldn't
 * lead anywhere - e.g. no tip method configured, or no social links set.
 *
 * Written in Claude, placed byte-for-byte by the agent, SHA-verified.
 * Do not edit this file in Emergent.
 */
export default function SongPlayedThanksModal({
  visible,
  songTitle,
  songArtist,
  showTip = true,
  showFollow = true,
  onTip,
  onFollow,
  onDismiss
}) {
  if (!visible) return null;

  const songLabel = songTitle
    ? (songArtist ? `"${songTitle}" by ${songArtist}` : `"${songTitle}"`)
    : 'Your song';

  return (
    <div
      className="fixed inset-0 bg-black/65 backdrop-blur-sm flex items-center justify-center z-50 p-4"
      data-testid="song-played-thanks-overlay"
    >
      <div className="bg-gray-800 border border-white/10 rounded-2xl p-7 w-full max-w-sm text-center relative shadow-2xl">
        <button
          onClick={onDismiss}
          className="absolute top-3 right-3 text-gray-500 hover:text-white text-xl leading-none p-1"
          data-testid="song-played-thanks-close"
        >
          ×
        </button>

        <div className="text-4xl mb-2">🎉</div>
        <p className="text-purple-400 text-xs font-bold uppercase tracking-wide mb-2">
          ✅ {songLabel} was just played
        </p>
        <p className="text-white text-lg font-extrabold mb-6 leading-snug">
          How would you like to say thanks?
        </p>

        {showTip && (
          <button
            onClick={onTip}
            className="w-full bg-gradient-to-r from-purple-600 to-pink-600 hover:from-purple-700 hover:to-pink-700 text-white font-bold py-3 rounded-lg mb-2.5 transition duration-300"
            data-testid="song-played-thanks-tip"
          >
            💰 Tip
          </button>
        )}

        {showFollow && (
          <button
            onClick={onFollow}
            className="w-full bg-white/5 hover:bg-white/10 border border-white/10 text-gray-200 font-semibold py-3 rounded-lg mb-3 transition duration-300"
            data-testid="song-played-thanks-follow"
          >
            📱 Follow
          </button>
        )}

        <button
          onClick={onDismiss}
          className="text-gray-500 hover:text-gray-300 text-xs"
          data-testid="song-played-thanks-maybe-later"
        >
          Maybe later
        </button>
      </div>
    </div>
  );
}
