import { useState, useEffect, useCallback, useRef } from 'react';
import axios from 'axios';

/**
 * useThanksTracking.js
 *
 * Tracks every song request an audience member submits on this device (per
 * musician slug), polls a public no-auth endpoint (POST /requests/status-check)
 * for their current status, and surfaces ONE at a time when a request's
 * status becomes "played" so the page can show a "how would you like to say
 * thanks?" prompt.
 *
 * Persists across page reloads and across days via localStorage: an audience
 * member who closes the tab before their song plays and reopens the same
 * link tomorrow still sees the thanks prompt if it hasn't been dismissed yet.
 * A tracked request is only ever removed by an explicit call to
 * dismissPendingThanks() (the caller decides that Tip, Follow, and "Maybe
 * later" all count as dismissal - there is no separate seen-but-not-dismissed
 * state), by the backend no longer returning it (deleted), by its status
 * coming back "rejected" (no thanks prompt is ever shown for a rejected
 * request), or after 14 days as a safety net against a request that somehow
 * never got dismissed.
 *
 * If someone requests more than one song, every request they submit is
 * tracked independently - if two of their songs get played, they'll see two
 * separate thanks prompts, one at a time, oldest first.
 *
 * Self-contained: own axios import, own API const, own localStorage keys.
 * No auth token is ever read or sent - the status-check endpoint is public.
 *
 * Written in Claude, placed byte-for-byte by the agent, SHA-verified.
 * Do not edit this file in Emergent.
 */

const API = `${process.env.REACT_APP_BACKEND_URL}/api`;

const STORAGE_PREFIX = 'requestwave_thanks_tracking_';
const POLL_INTERVAL_MS = 20000;
const MAX_TRACKED = 25; // defensive cap - a normal night never gets close to this
const MAX_AGE_MS = 14 * 24 * 60 * 60 * 1000; // 14 days

function loadTracked(slug) {
  try {
    const raw = localStorage.getItem(STORAGE_PREFIX + slug);
    if (!raw) return [];
    const parsed = JSON.parse(raw);
    if (!Array.isArray(parsed)) return [];
    const cutoff = Date.now() - MAX_AGE_MS;
    return parsed.filter((r) => r && typeof r.id === 'string' && r.submitted_at && new Date(r.submitted_at).getTime() > cutoff);
  } catch (e) {
    return [];
  }
}

function saveTracked(slug, list) {
  try {
    localStorage.setItem(STORAGE_PREFIX + slug, JSON.stringify(list.slice(-MAX_TRACKED)));
  } catch (e) {
    /* localStorage unavailable or full - tracking just won't persist this session, not fatal */
  }
}

export default function useThanksTracking(slug) {
  const [tracked, setTracked] = useState(() => (slug ? loadTracked(slug) : []));
  const trackedRef = useRef(tracked);
  trackedRef.current = tracked;

  const updateTracked = useCallback((updater) => {
    setTracked((prev) => {
      const next = updater(prev);
      if (slug) saveTracked(slug, next);
      trackedRef.current = next;
      return next;
    });
  }, [slug]);

  // Reload from localStorage whenever the slug changes (e.g. navigating between musicians)
  useEffect(() => {
    const loaded = slug ? loadTracked(slug) : [];
    trackedRef.current = loaded;
    setTracked(loaded);
  }, [slug]);

  // Registers a freshly-submitted request for tracking. Pass the full
  // request object returned by POST /requests (needs id, song_title,
  // song_artist, created_at).
  const trackRequest = useCallback((request) => {
    if (!slug || !request || !request.id) return;
    updateTracked((prev) => {
      if (prev.some((r) => r.id === request.id)) return prev; // already tracked, don't duplicate
      return [
        ...prev,
        {
          id: request.id,
          song_title: request.song_title || '',
          song_artist: request.song_artist || '',
          status: request.status || 'pending',
          submitted_at: request.created_at || new Date().toISOString()
        }
      ];
    });
  }, [slug, updateTracked]);

  // Call when the audience member has acted on (or explicitly dismissed) the
  // thanks prompt for this request id - it will never be shown again.
  const dismissPendingThanks = useCallback((requestId) => {
    updateTracked((prev) => prev.filter((r) => r.id !== requestId));
  }, [updateTracked]);

  // Poll every tracked request's current status on a fixed interval. The
  // interval itself is set up once per slug and always reads the latest
  // tracked list via trackedRef, so adding/dismissing a tracked request
  // doesn't reset the timer.
  useEffect(() => {
    if (!slug) return;
    let cancelled = false;

    const poll = async () => {
      const ids = trackedRef.current.map((r) => r.id);
      if (ids.length === 0) return;
      try {
        const response = await axios.post(`${API}/requests/status-check`, { request_ids: ids });
        if (cancelled) return;
        const byId = {};
        (response.data?.requests || []).forEach((r) => { byId[r.id] = r; });

        updateTracked((prev) => prev
          // Drop anything the backend no longer knows about (deleted), and
          // anything rejected - no thanks prompt is ever shown for those.
          .filter((r) => byId[r.id] && byId[r.id].status !== 'rejected')
          .map((r) => ({ ...r, status: byId[r.id].status }))
        );
      } catch (error) {
        console.error('Error checking request statuses for thanks tracking:', error);
        // Transient network error - just try again next tick, don't drop anything
      }
    };

    poll();
    const interval = setInterval(poll, POLL_INTERVAL_MS);
    return () => {
      cancelled = true;
      clearInterval(interval);
    };
  }, [slug, updateTracked]);

  // Oldest tracked request currently sitting at "played" and not yet
  // dismissed - null if none. Once dismissed, the next-oldest (if any)
  // becomes pendingThanks automatically on the next render.
  const pendingThanks = tracked.find((r) => r.status === 'played') || null;

  return { trackRequest, pendingThanks, dismissPendingThanks };
}
